name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectKey: liotier_Geogizmos
          organization: liotier      # Your SonarCloud org (as on https://sonarcloud.io/organizations/liotier/projects)
          token: ${{ secrets.SONAR_TOKEN }}
